export const creators=[
 {id:'elena',name:'Elena Voss',initials:'EV',category:'Style',descriptor:'Style & culture',location:'Paris, France',image:'atelier',bio:'A wardrobe as a point of view. Notes on personal style, considered objects, and the art of choosing well.'},
 {id:'sera',name:'Sera Lin',initials:'SL',category:'Beauty',descriptor:'Beauty & daily rituals',location:'Copenhagen, Denmark',image:'ritual',bio:'Less on the shelf, more intention in the day. Thoughtful routines and the objects that make them feel personal.'},
 {id:'julian',name:'Julian Dax',initials:'JD',category:'Design',descriptor:'Architecture & spaces',location:'Lisbon, Portugal',image:'architecture',bio:'Looking closer at the spaces we inhabit. Architecture, proportion, and the beauty of leaving room.'},
 {id:'ivy',name:'Ivy Rena',initials:'IR',category:'Culture',descriptor:'Photography & observation',location:'Milan, Italy',image:'architecture',bio:'A notebook of light, shadow, and overlooked details. Finding a photograph in an ordinary afternoon.'}
];
export const tiers=[
 {id:'essential',name:'Essential',price:9,level:1,description:'A closer look at the work.',features:['All circle entries','The complete entry archive','Members’ conversation']},
 {id:'premium',name:'Premium',price:19,level:2,description:'More context. More connection.',features:['Everything in Essential','In-depth studio notes','Priority conversation prompts']},
 {id:'signature',name:'Signature',price:39,level:3,description:'Inside the creative process.',features:['Everything in Premium','Signature reference collections','Private workshop notes']}
];
export const seedEntries=[
 {id:'p1',creatorId:'elena',title:'The pieces you return to.',subtitle:'On finding a personal uniform, and the freedom of choosing well.',category:'Style',format:'Essay',image:'atelier',minutes:4,access:'public',status:'published',date:'2026-09-30T09:00:00Z',body:'The most useful question in a wardrobe is not “What is missing?” It is “What keeps coming back?”\n\nFor a week, I photographed what I actually wore. Not the version of myself I imagined, but the one who walked to the bakery, took the train, and stayed late at the studio. A shape emerged: a generous coat, a narrow trouser, a shoe I could forget about.\n\nA personal uniform does not have to look the same every day. It needs a consistent logic. Mine begins with proportion: one generous volume, one clean line, one detail with a little tension. A borrowed shirt against a carefully cut jacket. A worn leather belt with something precise.\n\nStart with five pieces you already reach for. Lay them together and look for the conversation between them. Is it a colour? A texture? The way the fabric moves? That is the beginning of a point of view.\n\nThen make a small rule for the next thing you buy: it must make three of those pieces feel more like you. Not more current. More yours.\n\nThis week’s exercise: wear one favourite piece three ways. Notice which version lets you stop thinking about your clothes. That is usually the one worth keeping.'},
 {id:'p2',creatorId:'sera',title:'A slower start.',subtitle:'A small ritual, before the rest of the day arrives.',category:'Beauty',format:'Guide',image:'ritual',minutes:3,access:'public',status:'published',date:'2026-09-29T09:00:00Z',body:'For a long time, my morning routine was a list of things to finish. Now I think of it as a small space to enter.\n\nI put my phone in another room, open the curtains, and give the first cup of tea my full attention. Nothing particularly impressive happens. That is the point.\n\nThe objects on my shelf are few. A bowl I bought from a local ceramicist. A clean towel. The products I already know and enjoy. A routine is easier to keep when there is less to negotiate.\n\nTry choosing one ordinary moment tomorrow and leaving it uninterrupted. No recording, no optimisation. Just notice the weight of a cup, the temperature of the water, the light on the wall.\n\nA useful ritual is not one that looks good from the outside. It is one you are glad to return to.'},
 {id:'p3',creatorId:'julian',title:'Room to think.',subtitle:'What an empty corner can teach us about a considered space.',category:'Design',format:'Studio note',image:'architecture',minutes:5,access:'essential',status:'published',date:'2026-09-28T09:00:00Z',body:'An empty space is not necessarily unfinished. Sometimes it is the most deliberate part of a room.\n\nWhen I begin a project, I draw the movement before the furniture. Where does someone pause? Where does light fall in the late afternoon? Which view deserves to remain open?\n\nIn this stairwell, the wall does more than carry the structure. It edits what you see. The curve slows the eye and makes the small opening at the top feel larger than it is.\n\nYou can apply the same principle without rebuilding anything. Remove one object from a crowded surface. Move a chair out of a natural path. Leave a wall without a picture for a week.\n\nNotice whether the room becomes less complete, or simply more legible. The difference is subtle. A considered space lets the things you keep have enough room to matter.'},
 {id:'p4',creatorId:'elena',title:'The silhouette study.',subtitle:'Three proportions. One coat. A different way of seeing.',category:'Style',format:'Guide',image:'atelier',minutes:6,access:'premium',status:'published',date:'2026-09-27T09:00:00Z',body:'Before colour and detail, there is a shape. This studio note begins with that shape and works inward.\n\nFirst, photograph the outline. Stand against a plain wall, use natural light, and remove distractions from the frame. Squint at the image. What survives is the silhouette.\n\nStudy one: balance volume with a straight line. A substantial coat gains clarity above a narrow trouser. Let the hem and the shoe meet without an extra visual interruption.\n\nStudy two: repeat the volume. A wide trouser under a generous coat can work beautifully when the shoulders and waist remain intentional. The silhouette should feel like a decision, not a collection of accidents.\n\nStudy three: introduce contrast through texture rather than colour. Matte wool against polished leather. A soft scarf inside a precise collar. The eye finds the difference without having to work for it.\n\nMake three photographs, then put them away until tomorrow. Return without asking which is most flattering. Ask which feels most familiar to the person you want to be.'},
 {id:'p5',creatorId:'ivy',title:'Learning to notice.',subtitle:'A field note on shadows, repetition, and the everyday.',category:'Culture',format:'Field note',image:'architecture',minutes:3,access:'public',status:'published',date:'2026-09-26T09:00:00Z',body:'I took the same walk every afternoon for a month. The route was unremarkable: a courtyard, a narrow street, the back of a library.\n\nWhat changed was the light. A plain wall became a composition for twenty minutes, then returned to being a wall. A handrail drew a second staircase in shadow.\n\nTry this with a place you know well. Leave your camera in your bag for the first ten minutes. Look for repetition: the same shape in different materials, a line that continues across a doorway, a shadow that almost touches another.\n\nWhen you do make a photograph, take one step closer before pressing the shutter. Then one step back. The subject may stay the same, but the relationship changes.\n\nObservation is a practice of returning. You do not need a more interesting place. You need another look.'},
 {id:'p6',creatorId:'sera',title:'Objects with a purpose.',subtitle:'A shelf edited down to what earns its place.',category:'Beauty',format:'Collection',image:'ritual',minutes:4,access:'signature',status:'published',date:'2026-09-25T09:00:00Z',body:'This collection is an exercise in subtraction. Each object has a job, and each job has one object.\n\nThe ceramic bowl holds small things at the end of the day. The linen towel becomes softer with use. The glass bottle is something I can refill, rather than replace.\n\nI began by emptying the shelf completely. Anything that had not been touched in a month stayed in a box for another week. I did not miss most of it.\n\nWhat remained was not particularly coordinated. It was simply useful, pleasant to hold, and familiar. A collection can be coherent because of how it is used, not only how it looks.\n\nYour reference exercise: choose a single shelf. Take everything away, wipe it clean, and return only what you used this week. Live with that version before adding anything else.'}
];
export const sampleMembers=[{name:'Aria Bennett',email:'aria@example.com',tier:'premium',joined:'2026-09-02'},{name:'Noah Cole',email:'noah@example.com',tier:'essential',joined:'2026-09-08'},{name:'Mila Rhodes',email:'mila@example.com',tier:'signature',joined:'2026-09-13'},{name:'Sage Monroe',email:'sage@example.com',tier:'premium',joined:'2026-09-21'},{name:'Ethan Vale',email:'ethan@example.com',tier:'essential',joined:'2026-09-25'}];
export function initialState(){return {version:1,role:'member',profile:{name:'Aria Bennett',bio:'Collecting ideas worth returning to.'},following:['elena','sera'],saved:[],liked:[],memberships:{},entries:structuredClone(seedEntries),messages:[{id:'welcome-elena',creatorId:'elena',from:'creator',text:'Welcome to the circle. This is a space for the details that never fit in a caption. What would you like to explore next?',date:'2026-09-30T10:00:00Z',sample:true},{id:'welcome-sera',creatorId:'sera',from:'creator',text:'A small note for the week: leave room for a slower start. I’ve shared a new entry on the rituals I return to.',date:'2026-09-29T10:00:00Z',sample:true}],welcomeDismissed:false,preferences:{compact:false},read:[]};}
