import { icon } from './icons.js';
import { applySignedInCtas } from './views/auth/landing-session.js';
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
applySignedInCtas();
const menu=document.querySelector('[data-menu]');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');document.querySelector('.landing-header nav').classList.toggle('open',open)});
document.querySelectorAll('.landing-header nav a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.landing-header nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation')}));
const legal=document.querySelector('#legal');
document.querySelectorAll('[data-legal]').forEach(b=>b.addEventListener('click',()=>{const privacy=b.dataset.legal==='privacy';legal.innerHTML=`<div class="dialog-head"><h2 id="legal-title">${privacy?'Privacy':'About REFLUENZ'}</h2><button class="icon-button" aria-label="Close dialog">${icon('close')}</button></div><div class="dialog-body"><p>${privacy?'Your account, profile, reading list, memberships, messages and entries are stored with our database provider, Supabase, in the EU (Frankfurt) and protected by per-account access rules. Messages are visible only to you and the creator. There are no advertising trackers. You can export your data from Settings.':'REFLUENZ is in early access. Creating an account is free. Membership prices are shown for each tier, but payments are not live yet, so joining a circle costs nothing for now. You will be asked before anything is ever charged.'}</p><p>Never share payment details in messages. On a shared device, sign out when you finish.</p><a class="button" href="/app/settings">Open settings ${icon('arrow')}</a></div>`;legal.querySelector('button').onclick=()=>legal.close();legal.showModal()}));
legal.addEventListener('click',e=>{if(e.target===legal){const r=legal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)legal.close()}});

document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){document.querySelector('.landing-header nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.focus()}});
