import { initialState, creators, tiers } from './data.js';
export const STORAGE_KEY='refluenz.atelier.v1';
export const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function canRead(entry,state){if(entry.access==='public')return true;const need=tiers.find(t=>t.id===entry.access)?.level??99;const have=tiers.find(t=>t.id===state.memberships[entry.creatorId])?.level??0;return have>=need;}
export function validateEntry(values){const title=String(values.title??'').trim(),body=String(values.body??'').trim(),subtitle=String(values.subtitle??'').trim();if(title.length<3||title.length>100)throw Error('Use a title between 3 and 100 characters.');if(body.length<30||body.length>20000)throw Error('Write between 30 and 20,000 characters for your entry.');if(subtitle.length>180)throw Error('Keep the introduction under 180 characters.');if(!['public',...tiers.map(t=>t.id)].includes(values.access))throw Error('Choose a valid access level.');if(!['Style','Beauty','Design','Culture'].includes(values.category))throw Error('Choose a category.');if(!['atelier','ritual','architecture'].includes(values.image))throw Error('Choose a cover.');return {...values,title,body,subtitle,minutes:Math.max(1,Math.ceil(body.split(/\s+/).length/200))};}
export function createStore(storage){let state=initialState(),warning='';try{const raw=storage.getItem(STORAGE_KEY);if(raw){const saved=JSON.parse(raw);if(saved.version!==1||!Array.isArray(saved.entries)||!saved.entries.length||!saved.profile||!Array.isArray(saved.saved)||!Array.isArray(saved.messages))throw Error('Invalid saved data');state={...state,...saved};for(const key of ['following','saved','liked','read'])if(!Array.isArray(state[key]))state[key]=[];if(!state.memberships||typeof state.memberships!=='object')state.memberships={};if(!['member','creator'].includes(state.role))state.role='member';state.profile.name=String(state.profile.name||'Aria Bennett').slice(0,60);state.profile.bio=String(state.profile.bio||'').slice(0,240);state.entries=state.entries.filter(e=>e&&typeof e.id==='string'&&typeof e.body==='string'&&creators.some(c=>c.id===e.creatorId));}}}catch{warning='Saved data could not be loaded. A fresh demo is open; export anything important before resetting.';}
return {get state(){return state},warning,update(fn){const next=structuredClone(state);fn(next);try{storage.setItem(STORAGE_KEY,JSON.stringify(next))}catch{throw Error('Your browser could not save this change. Free some storage or allow site storage and try again.')}state=next;return state;},reset(){const next=initialState();try{storage.setItem(STORAGE_KEY,JSON.stringify(next))}catch{throw Error('Your browser could not reset the demo. Check site storage permissions.')}state=next;return state;}};}
export function toggle(list,value){const index=list.indexOf(value);if(index<0)list.push(value);else list.splice(index,1);}
export function membershipTotal(state){return Object.values(state.memberships).reduce((n,id)=>n+(tiers.find(t=>t.id===id)?.price||0),0)}
export function csvCell(value){const text=String(value);return '"'+(/^[=+\-@\t\r]/.test(text)?"'":'')+text.replaceAll('"','""')+'"'}
